### ISSUE TITLE
1.15.11 Patched IPA crashes on opening. (AltStore & Sideloadly install)

### ISSUE THREAD

**Issue by J0hnny007** [EthanArbuckle/Apollo-CustomApiCredentials#10]
IOS 16.5.1 / iPhone 11 Pro

I've tried now for some time to get it working only to be foiled by Apollo (patched) crashing on startup.

What works so far is:

Sideload spoofer disabled & no `THEOS_PACKAGE_SCHEME=rootless`

but that only gets me to the Testflight version that logs you out after a while. Kinda like in #3 .

**Comment by kristofferR** [comment]
Same issue here.

**Comment by paradoxally** [comment]
You need to turn off any data connection, open Apollo and sign out from your account(s).

Then you can quit the app and it won't crash when you open it again.

**Comment by J0hnny007** [comment]
From every device? Well, I cannot sign out anymore. Does deleting the app help? Or do I need to revoke Apollos API access?

**Comment by paradoxally** [comment]
It seems like Reddit is to blame.

https://mastodon.social/@christianselig/110635856662952525

It shouldn't crash anymore according to Christian, he deleted the token.

**Comment by kristofferR** [comment]
No, you are misunderstanding. We're not talking about the official app, we're talking about how the Sideload Spoofer in Sideloadly makes the app crash.

**Comment by paradoxally** [comment]
Oh. I did not sideload anything.

I am using the official app, signed by the App Store (v 1.15.11) and followed [these steps](https://old.reddit.com/r/apolloapp/comments/14iub7y/backup_apollo_app_version_0159_if_you_want_to_use/jpjqaf5/?context=3) to get it working again. Essentially, you use a man-in-the-middle proxy to inject the new key. This avoids having to resign every 7 days.

**Comment by kristofferR** [comment]
> Oh. I did not sideload anything.
> 
> I am using the official app, signed by the App Store (v 1.15.11)

Okay, perhaps you shouldn't participate in discussions of issues for projects you don't even use... It shouldn't be hard to read the title and realize that this discussion was not about MITMing the App Store app.

This thread is already full of misinformation and wasted posts because you joined in.

**Comment by paradoxally** [comment]
> > Oh. I did not sideload anything.
> > I am using the official app, signed by the App Store (v 1.15.11)
> 
> Okay, perhaps you shouldn't participate in discussions of issues for projects you don't even use... It shouldn't be hard to read the title and realize that this discussion was not about MITMing the App Store app.
> 
> This thread is already full of misinformation and wasted posts because you joined in.

My apologies. I have deleted the posts to avoid further confusion.

**Comment by EthanArbuckle** [comment]
Is this crash still happening?

**Comment by Barusu-rem** [comment]
> Is this crash still happening?

I'm not getting this issue (I used udidregistration dev certs, iosapp signer (mac), and sideloady (used sideload spoofer)

**Comment by Barusu-rem** [comment]
> From every device? Well, I cannot sign out anymore. Does deleting the app help? Or do I need to revoke Apollos API access?

> Well, looks like Reddit pulled the plug a little early. Apollo started crashing, but I just manually revoked my token and it looks like it fixes the crashing, but no more Reddit access haha. Those folks are fun to the very end! 😛

https://mastodon.social/@christianselig/110635856662952525

@EthanArbuckle 

not sure if this had anything to do with the crashes

**Comment by kristofferR** [comment]
> Is this crash still happening?

Yes, just tried again with the new updated code. When only Cydia Substrate is checked it launches fine and logs out all the time, when Sideload Spoofer is enabled it crashes at launch.

I'm only using Sideloadly.

**Comment by Barusu-rem** [comment]
> > Is this crash still happening?
> 
> Yes, just tried again with the new updated code. When only Cydia Substrate is checked it launches fine and logs out all the time, when Sideload Spoofer is enabled it crashes at launch.
> 
> I'm only using Sideloadly.

Can you try this version
https://github.com/Barusu-rem/apollo-decrypt-legacy-version/releases/download/production/Apollo_1.15.11_decrypt.ipa 

I noticed the bundled ipa wasn't showing an icon in sideloady and tried the decrypt.day version I got earlier (seems to work)

**Comment by godver3** [comment]
Same issue for me. Tried the rootless option as well. I’m on 16.1.1 and used Sideloadly to install.

**Comment by RohitK89** [comment]
@J0hnny007 et al. This is caused because you're using the same bundle ID as the actual Apollo app. Steps to fix if using Sideloadly:

1. Uncheck the box that says `Use automatic bundle ID`
2. Change `com.christianselig.Apollo` to anything else (but keep the structure the same, i.e. `com.something.Apollo`.
3. Follow the remaining steps the same way, i.e. inject dylib, check `Sideload spoofer`, check `Cydia Substrate`
4. Load the app on your phone

Should be good to go!

**Comment by FlipABit** [comment]
> @J0hnny007 et al. This is caused because you're using the same bundle ID as the actual Apollo app. Steps to fix if using Sideloadly:
> 
> 1. Uncheck the box that says `Use automatic bundle ID`
> 2. Change `com.christianselig.Apollo` to anything else (but keep the structure the same, i.e. `com.something.Apollo`.
> 3. Follow the remaining steps the same way, i.e. inject dylib, check `Sideload spoofer`, check `Cydia Substrate`
> 4. Load the app on your phone
> 
> Should be good to go!

This doesn't work for me. Checking "Sideload spoofer" is what causes the crash no matter if I change the bundle ID or not. Unchecking "Sideload Spoofer" makes it load fine but I get the constant logouts. I'm on 16.5.1 (jailed) installing via AltStore.

**Comment by sbeck14** [comment]
> @J0hnny007 et al. This is caused because you're using the same bundle ID as the actual Apollo app. Steps to fix if using Sideloadly:
> 
> 1. Uncheck the box that says `Use automatic bundle ID`
> 2. Change `com.christianselig.Apollo` to anything else (but keep the structure the same, i.e. `com.something.Apollo`.
> 3. Follow the remaining steps the same way, i.e. inject dylib, check `Sideload spoofer`, check `Cydia Substrate`
> 4. Load the app on your phone
> 
> Should be good to go!

This fixes the crashes for me, installing via Sideloadly

**Comment by nicko88** [comment]
The app works for me, but if it fully closes, it signs me out every time.

**Comment by J0hnny007** [comment]
Good morning everyone, and thanks for the instructions @RohitK89. I tried it on my iPad and it works via Sideloadly install without a hitch, just need to find a better way to manage my apps now with AltStore+Sideloadly.

**Comment by dmginc** [comment]
Any idea why I'm getting this error while trying to sideload? No matter what I rename it to..
`Failed: (9401) An App ID with Identifier 'com.something.Apollo' is not available. Please enter a different string.`

Edit: restarted sideloadly and it works just fine now...
