### ISSUE TITLE
The .theos folder is missing in when I try to install the ApiCredentials,

### ISSUE THREAD

**Issue by TheMysteriousWarlock** [EthanArbuckle/Apollo-CustomApiCredentials#12]
I've hit a roadblock when trying to make package with me being given the following:

```
nonrootXXXXX@MYPC:~/Apollo-CustomApiCredentials$ make package
Makefile:14: /tweak.mk: No such file or directory
make: *** No rule to make target '/tweak.mk'.  Stop.
```
I'm not sure if this is also directly related, but I have a theory that it might be related to how I can't properly install the swift toolchain as seen below. I'm on my non-root user which has SU perms, but no matter what I do I can't get it to installed.
``
==> Checking for iOS toolchain...

==> A toolchain does not appear to be installed.
``
Warning: Failed to create the file swift-5.3.2-RELEASE-ubuntu20.04.tar.zst:
Warning: Permission denied
curl: (23) Failure writing output to destination
``

**Comment by EthanArbuckle** [comment]
`$THEOS` needs to point to theos https://github.com/theos/theos

**Comment by TheMysteriousWarlock** [comment]
> `$THEOS` needs to point to theos https://github.com/theos/theos

How do I point $THEOS to theos?
