### ISSUE TITLE
Error in connecting to reddit account

### ISSUE THREAD

**Issue by buyinginquiries** [EthanArbuckle/Apollo-CustomApiCredentials#13]
Even with the script and checking the boxes, getting an error that says 

Error: Error fetching oauth client.
at request OauthApp

I have ticked the Cydia substrate boxes, included the dylibs, sideloaded the spoofer.
Logged mitm to see and it was correctly sending a get request from my supplied API key, but seems like the redirect is wrong

**Comment by Exitious** [comment]
I have this issue. What was the solution? @buyinginquiries

**Comment by EthanArbuckle** [comment]
@Exitious make sure you pick "installed app" when creating the api credentials on reddit

using this branch will automate the creation of the credentials: https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/tree/in-app-credential-creation
