### ISSUE TITLE
API screen incorrectly being called

### ISSUE THREAD

**Issue by Bchass** [EthanArbuckle/Apollo-CustomApiCredentials#14]
I noticed after clicking on a picture or a link, the api configuration screen keeps being called. 

Attached is a video to show the behavior.

https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/34097574/0d45e557-fc33-4131-95d4-fc90f792ffeb

**Comment by nicko88** [comment]
Wrong GitHub. That’s a different tweak.
