### ISSUE TITLE
Logs out every time app is closed

### ISSUE THREAD

**Issue by scratchyone** [EthanArbuckle/Apollo-CustomApiCredentials#15]
I patched an Apollo IPA with this tweak using theos-jailed, and while it works great, it seems to log out every time the app is restarted. Any ideas why this may be?

**Comment by nicko88** [comment]
I sideloaded with a dev account with sideloadly with a new bundle ID and mine does this too if I fully close the app and re-open.

**Comment by scratchyone** [comment]
Hmm, I just tried it with the standard Apollo com.christianselig.Apollo bundle ID and it has the same issue.

**Comment by AuroraWright** [comment]
You can fix it by injecting this https://sideloadly.io/SideloadSpoofer-08.dylib and using a different bundle ID than the stock one, but it would be nice to have an open source alternative because it shows a popup every time you restart the app and it being closed source isn't great.

**Comment by Rihcus** [comment]
https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/issues/3#issuecomment-1599651447

**Comment by ochompsky** [comment]
> You can fix it by injecting this https://sideloadly.io/SideloadSpoofer-08.dylib and using a different bundle ID than the stock one, but it would be nice to have an open source alternative because it shows a popup every time you restart the app and it being closed source isn't great.

i assume this requires a JB?  my app crashes immediately on boot when i try to inject

**Comment by AuroraWright** [comment]
> > You can fix it by injecting this https://sideloadly.io/SideloadSpoofer-08.dylib and using a different bundle ID than the stock one, but it would be nice to have an open source alternative because it shows a popup every time you restart the app and it being closed source isn't great.
> 
> i assume this requires a JB? my app crashes immediately on boot when i try to inject

No, no jb

**Comment by scratchyone** [comment]
> You can fix it by injecting this https://sideloadly.io/SideloadSpoofer-08.dylib and using a different bundle ID than the stock one, but it would be nice to have an open source alternative because it shows a popup every time you restart the app and it being closed source isn't great.

Thanks for suggesting this, it solves the problem! I also found https://github.com/level3tjg/RedditSideloadFix/releases/tag/1, which is actually meant to fix sideloading for the official reddit app, but seems to also fix the logging out issue on Apollo in my testing, and it's open source and doesn't show any prompt. I'd love if anyone else could confirm if this works for them as well?

**Comment by EthanArbuckle** [comment]
When sideloading, its necessary to change Apollo's bundle ID. Otherwise, information stored in the keychain will not persist across app launches.

I'll see if I can workaround this in the tweak

**Comment by asdfzxcvbn** [comment]
> > You can fix it by injecting this https://sideloadly.io/SideloadSpoofer-08.dylib and using a different bundle ID than the stock one, but it would be nice to have an open source alternative because it shows a popup every time you restart the app and it being closed source isn't great.
> 
> Thanks for suggesting this, it solves the problem! I also found https://github.com/level3tjg/RedditSideloadFix/releases/tag/1, which is actually meant to fix sideloading for the official reddit app, but seems to also fix the logging out issue on Apollo in my testing, and it's open source and doesn't show any prompt. I'd love if anyone else could confirm if this works for them as well?

can confirm this works great! i didnt have to inject sideload spoofer or change the bundle id
