### ISSUE TITLE
Logs out when I close the app

### ISSUE THREAD

**Issue by KernelFox0** [EthanArbuckle/Apollo-CustomApiCredentials#16]
iOS Version: 16.5
App version: 1.5.11
Sideloaded with AltStore

Every time I close the app it logs me out and I need to log in again.
When I enable sideload spoofer and change bundle ID, it just crashes on open. I also tried to sideload with Sideloadly but it still crashes.
If I just change bundle ID the app opens but has the logout problem.

**Comment by Gregulator87** [comment]
This issue is already solved. You need to rename the bundle ID
https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/issues/10#issuecomment-1615405235

**Comment by KernelFox0** [comment]
> This issue is already solved. You need to rename the bundle ID

I did that. Nothing changed.

**Comment by KernelFox0** [comment]
> > This issue is already solved. You need to rename the bundle ID
> 
> I did that. Nothing changed.

Nevermind it started working with sideloadly instead of altstore.
