### ISSUE TITLE
Apollo API Popup Happening Constantly

### ISSUE THREAD

**Issue by danielschwartz** [EthanArbuckle/Apollo-CustomApiCredentials#17]
Thanks for this tweak, it's awesome! That being said, every time I leave the app and come back or I view an image/video and then go back to my feed the informational Apollo API popup happens meaning I have to constantly hit "continue" in that popup to keep using Apollo. I've already gone through the steps to add a custom API key and it's working great. It's just the constant popup that's annoying.

The popup i'm talking about is the one in the screenshot below
![IMG_79B8A2D91213-1](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/505433/c4f9a94b-7de3-42d2-8972-0a9c524aa658)

**Comment by EthanArbuckle** [comment]
that is a different tweak

**Comment by danielschwartz** [comment]
D'oh, you are right. Sorry about that!
