### ISSUE TITLE
Error fetching oauth client

### ISSUE THREAD

**Issue by Exitious** [EthanArbuckle/Apollo-CustomApiCredentials#19]
When trying to sign in with reddit, I get an error trying to connect the reddit account. I see an issue talking about this that was closed, but no solution seems to have been mentioned.

**Comment by Jampuppy10** [comment]
I figured it out. When i setup the api app. the phone autocorrected apollo to have a capital A. make sure to check your spelling when you setup the api

**Comment by Exitious** [comment]
Thank you @Jampuppy10, I went back and checked the redirect uri several times, yet I never noticed that I had input "redirect-oauth" instead of "reddit-oauth." I don't know how I didn't notice.
