### ISSUE TITLE
Getting auto logged out

### ISSUE THREAD

**Issue by Rihcus** [EthanArbuckle/Apollo-CustomApiCredentials#3]
I noticed a weird issue where you can log into your reddit account (post, view saved posts, etc), however once you close and reopen apollo it reprompts to sign in.

**Comment by BoxIsMyNamee** [comment]
I can attest to this. Exact same thing happens to me.

**Comment by Joshua-Noakes1** [comment]
This is happening to me too. I'm using iOS 17 beta if it could be the issue.

**Comment by aj-swartz** [comment]
> I'm using iOS 17 beta if it could be the issue.

palera1n or a substrate injected IPA?

**Comment by Joshua-Noakes1** [comment]
> > I'm using iOS 17 beta if it could be the issue.
> 
> palera1n or a substrate injected IPA?

substrate signed with both altstore and sideloadly using a non dev apple account

**Comment by BoxIsMyNamee** [comment]
ok so. I’ve figured out that regardless of this tweak or not. Sideloaded Apollo always registers as the testflight beta (for some reason) and always logs out. so this has turned into a bigger issue. I was thinking maybe we could find a pirated copy of apollo where those issues are fixed and then apply this to that. but idk. 

i’ve found a quicker way to sign into the app each time tho. Click sign in, then cancel and it’ll prompt some options. Select “Issues with signing in” and it should auto bring you up to the reddit allow page. skipping the actual typing in of your details.

**Comment by Rihcus** [comment]
> ok so. I’ve figured out that regardless of this tweak or not. Sideloaded Apollo always registers as the testflight beta (for some reason) and always logs out. so this has turned into a bigger issue. I was thinking maybe we could find a pirated copy of apollo where those issues are fixed and then apply this to that. but idk.
> 
> i’ve found a quicker way to sign into the app each time tho. Click sign in, then cancel and it’ll prompt some options. Select “Issues with signing in” and it should auto bring you up to the reddit allow page. skipping the actual typing in of your details.

Got it fixed (unintentionally) :)

![IMG_0479](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/30292597/2adbd0a7-df41-490a-8988-9d8e7c29bb9a)


Make sure to enable Sideload spoofer on sideloady.

Also once you inject the tweak and sign in you should see your app name for the consent screan instead of apollo's

 
![IMG_0476 2](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/30292597/d0d5dad6-633f-49d8-93a2-d1e82cafb5be)

Also you should get a tweak is working! message on every launch of apollo
![IMG_424FFAB2301F-1](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/30292597/d7e36120-b02e-4d4b-a39e-848777355b5e)

Multiple accounts work, posting works, sending comments works.

Only features that seem to be broken
- No community icons 
- Imgur upload is broken
- Push notifications are broken
- The open in apollo safari extension isn't automatic (it will redirect you to openinapollo.com but you have to manually click the open in apollo button).

**Comment by godver3** [comment]
> > ok so. I’ve figured out that regardless of this tweak or not. Sideloaded Apollo always registers as the testflight beta (for some reason) and always logs out. so this has turned into a bigger issue. I was thinking maybe we could find a pirated copy of apollo where those issues are fixed and then apply this to that. but idk.
> > i’ve found a quicker way to sign into the app each time tho. Click sign in, then cancel and it’ll prompt some options. Select “Issues with signing in” and it should auto bring you up to the reddit allow page. skipping the actual typing in of your details.
> 
> Got it fixed (unintentionally) :)
> 

Are you jailbroken? This isn't working for me unfortunately. The app crashes immediately on launch.

**Comment by Rihcus** [comment]
> > > ok so. I’ve figured out that regardless of this tweak or not. Sideloaded Apollo always registers as the testflight beta (for some reason) and always logs out. so this has turned into a bigger issue. I was thinking maybe we could find a pirated copy of apollo where those issues are fixed and then apply this to that. but idk.
> > > i’ve found a quicker way to sign into the app each time tho. Click sign in, then cancel and it’ll prompt some options. Select “Issues with signing in” and it should auto bring you up to the reddit allow page. skipping the actual typing in of your details.
> > 
> > 
> > Got it fixed (unintentionally) :)
> 
> Are you jailbroken? This isn't working for me unfortunately. The app crashes immediately on launch.

No sideloaded on iPadOS 16.5. Did you make sure to enable rootless mode in the tweak?

**Comment by Rihcus** [comment]
> > > ok so. I’ve figured out that regardless of this tweak or not. Sideloaded Apollo always registers as the testflight beta (for some reason) and always logs out. so this has turned into a bigger issue. I was thinking maybe we could find a pirated copy of apollo where those issues are fixed and then apply this to that. but idk.
> > > i’ve found a quicker way to sign into the app each time tho. Click sign in, then cancel and it’ll prompt some options. Select “Issues with signing in” and it should auto bring you up to the reddit allow page. skipping the actual typing in of your details.
> > 
> > 
> > Got it fixed (unintentionally) :)
> 
> Are you jailbroken? This isn't working for me unfortunately. The app crashes immediately on launch.

Also if this help this is the guide I used (only difference was I made sure to use sideload spoofer)

https://www.reddit.com/r/jailbreak/comments/145y787/tutorial_how_to_add_your_own_api_key_to_apollo/ 

https://cryptpad.disroot.org/pad/#/2/pad/view/6CVxyIk0GZ7xeEyFnDdIb-IqZKoAEHAY1EPjQjlbRZs/embed/

[Apollo-Api-mod-backup-r_jailbreak.md](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/files/11816913/Apollo-Api-mod-backup-r_jailbreak.md)

**Comment by godver3** [comment]
This was the part I missed (I think the original tutorial I followed didn't
cover this bit):

FOR ROOTLESS JAILBREAK: Open Makefile and add the following line:
THEOS_PACKAGE_SCHEME=rootless

Thanks for the tip.

**Comment by Z3ROS1X** [comment]
> > > > ok so. I’ve figured out that regardless of this tweak or not. Sideloaded Apollo always registers as the testflight beta (for some reason) and always logs out. so this has turned into a bigger issue. I was thinking maybe we could find a pirated copy of apollo where those issues are fixed and then apply this to that. but idk.
> > > > i’ve found a quicker way to sign into the app each time tho. Click sign in, then cancel and it’ll prompt some options. Select “Issues with signing in” and it should auto bring you up to the reddit allow page. skipping the actual typing in of your details.
> > > 
> > > 
> > > Got it fixed (unintentionally) :)
> > 
> > 
> > Are you jailbroken? This isn't working for me unfortunately. The app crashes immediately on launch.
> 
> Also if this help this is the guide I used (only difference was I made sure to use sideload spoofer)
> 
> [reddit.com/r/jailbreak/comments/145y787/tutorial_how_to_add_your_own_api_key_to_apollo](https://www.reddit.com/r/jailbreak/comments/145y787/tutorial_how_to_add_your_own_api_key_to_apollo/)
> 
> [cryptpad.disroot.org/pad/#/2/pad/view/6CVxyIk0GZ7xeEyFnDdIb-IqZKoAEHAY1EPjQjlbRZs/embed](https://cryptpad.disroot.org/pad/#/2/pad/view/6CVxyIk0GZ7xeEyFnDdIb-IqZKoAEHAY1EPjQjlbRZs/embed/)
> 
> [Apollo-Api-mod-backup-r_jailbreak.md](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/files/11816913/Apollo-Api-mod-backup-r_jailbreak.md)

What does the “Sideload spoofer” option do? I created my IPA without that option ticked in Sideloadly and it works without it, however I don’t get a banner saying the tweak is working when I launch Apollo. I guess I can rebuild the IPA and see what happens.

**Comment by Rihcus** [comment]
> What does the “Sideload spoofer” option do? I created my IPA without that option ticked in Sideloadly and it works without it, however I don’t get a banner saying the tweak is working when I launch Apollo. I guess I can rebuild the IPA and see what happens.

Not exactly sure. The tweak is working prompt is from the sideload fixer patch not directly from the oath patch.

From my testing without the sideloadfixer patch account logouts occur after every reboot.

**Comment by Z3ROS1X** [comment]
> > What does the “Sideload spoofer” option do? I created my IPA without that option ticked in Sideloadly and it works without it, however I don’t get a banner saying the tweak is working when I launch Apollo. I guess I can rebuild the IPA and see what happens.
> 
> Not exactly sure. The tweak is working prompt is from the sideload fixer patch not directly from the oath patch.
> 
> From my testing without the sideloadfixer patch account logouts occur after every reboot.

I rebuilt my IPA for sideloading with Sideload Spoofer enabled this time and the only difference in notifying is that upon every launch of Apollo there is a green banner popup stating that the Custom API tweak is working. The app is now NOT logging me out every time the app closes from the App Switcher/multitasking, unlike before. What is the “Sideload fixer patch”? Is that what Sideload Spoofer is? Cause that’s the only difference I made this time and it’s keeping me logged in. Just no notifications.

**Comment by BoxIsMyNamee** [comment]
> > > What does the “Sideload spoofer” option do? I created my IPA without that option ticked in Sideloadly and it works without it, however I don’t get a banner saying the tweak is working when I launch Apollo. I guess I can rebuild the IPA and see what happens.
> > 
> > 
> > Not exactly sure. The tweak is working prompt is from the sideload fixer patch not directly from the oath patch.
> > From my testing without the sideloadfixer patch account logouts occur after every reboot.
> 
> I rebuilt my IPA for sideloading with Sideload Spoofer enabled this time and the only difference in notifying is that upon every launch of Apollo there is a green banner popup stating that the Custom API tweak is working. The app still logs me out every time the app closes from the App Switcher/multitasking, however. What is the “Sideload fixer patch”? Is that what Sideload Spoofer is?

did you add the THEOS_PACKAGE_SCHEME=rootless line to the make file

**Comment by Z3ROS1X** [comment]
> > > > What does the “Sideload spoofer” option do? I created my IPA without that option ticked in Sideloadly and it works without it, however I don’t get a banner saying the tweak is working when I launch Apollo. I guess I can rebuild the IPA and see what happens.
> > > 
> > > 
> > > Not exactly sure. The tweak is working prompt is from the sideload fixer patch not directly from the oath patch.
> > > From my testing without the sideloadfixer patch account logouts occur after every reboot.
> > 
> > 
> > I rebuilt my IPA for sideloading with Sideload Spoofer enabled this time and the only difference in notifying is that upon every launch of Apollo there is a green banner popup stating that the Custom API tweak is working. The app still logs me out every time the app closes from the App Switcher/multitasking, however. What is the “Sideload fixer patch”? Is that what Sideload Spoofer is?
> 
> did you add the THEOS_PACKAGE_SCHEME=rootless line to the make file

No, because like I stated I’m sideloading the app on jailed iOS 16.1.2 (with MacDirtyCow tweaks). I don’t need that line unless I would be jailbreaking.
