### ISSUE TITLE
Can no longer load any posts or subreddits?

### ISSUE THREAD

**Issue by rebelancap** [EthanArbuckle/Apollo-CustomApiCredentials#38]
Been using this patch every day since app was sunsetted. But just now, it stopped working. Can't load any subreddits, multireddits, or posts. Long loading icon then says it has "no posts." Anyone else?

**Comment by coryshaw1** [comment]
Reddit started blocking Apollo's user agent which is why things aren't loading. There are other forks of this repo that are being updated to address this.

I use [ichitaso/ApolloPatcher](https://github.com/ichitaso/ApolloPatcher)

**Comment by EthanArbuckle** [comment]
fixed in 1.0.2
