### ISSUE TITLE
Imgur key patch

### ISSUE THREAD

**Issue by Rihcus** [EthanArbuckle/Apollo-CustomApiCredentials#5]
Not confirmed yet but I think apollo may have disabled their imigur upload feature. (Tested via paid app store version)

![IMG_0475](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/30292597/989d390a-305e-4ca1-8913-869bce3d74f8)
![IMG_0471](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/30292597/181c703f-f003-434e-bde3-a4909893078e)

**Comment by paradoxally** [comment]
Christian mentioned he paid Imgur for users to upload media via Apollo. I expect he has shut down his API key. 

I wonder if we can override the default API key and get this working again.

**Comment by EthanArbuckle** [comment]
indeed we can. I plan t osupport this soon, just been busy with other stuff

**Comment by Z3ROS1X** [comment]
> indeed we can. I plan t osupport this soon, just been busy with other stuff

Amazing, I look forward to you supporting this feature down the road! In the meantime I’m uploading images in the Imgur app and copying the link for Apollo. Extra steps, but at least it works for now.

**Comment by Rihcus** [comment]
> > indeed we can. I plan t osupport this soon, just been busy with other stuff
> 
> Amazing, I look forward to you supporting this feature down the road! In the meantime I’m uploading images in the Imgur app and copying the link for Apollo. Extra steps, but at least it works for now.

As another work around for the time being you can use ios shortcuts (imgur is baked in no 3rd party app required plus it has the benefit of allowing to directly copy the image link)

https://www.icloud.com/shortcuts/fee1958a30e942ceb319381258b4d21e

**Comment by EthanArbuckle** [comment]
you can provide your own Imgur credentials now. Apollo uses RapidAPI https://rapidapi.com/imgur/api/imgur-9

**Comment by Barusu-rem** [comment]
> you can provide your own Imgur credentials now. Apollo uses RapidAPI https://rapidapi.com/imgur/api/imgur-9

Hope I don't sill but what options did you choose when registering the api?

https://api.imgur.com/oauth2/addclient 
<img width="774" alt="image" src="https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/124480833/32760e5b-f0a9-4f2a-9d3f-808abf1b563b">

not sure if I'm doing something wrong
