### ISSUE TITLE
API Rate limits 

### ISSUE THREAD

**Issue by Rihcus** [EthanArbuckle/Apollo-CustomApiCredentials#7]
Does anyone know how many api calls apollo normally uses? More importantly is it possible for apollo to exceed 100 api calls per min on normal use?

Another issue we may run into is prior to logging in apollo would be limited to 10 api calls per min (ie not using Oath). I was wondering if their is a way to prevent apollo from loading any messages prior to logging in (in order to avoid triggering a rate limit on first login).

As of July 1, 2023, we will enforce two different rate limits for those eligible for free access usage of our Data API. The limits are:   

    If you are using OAuth for authentication: 100 queries per minute (QPM) per OAuth client id
    If you are not using OAuth for authentication: 10 QPM

https://www.redditinc.com/policies/data-api-terms

**Comment by paradoxally** [comment]
Hi @Rihcus,

You can see how many requests Apollo is sending by running [Charles Proxy](https://www.charlesproxy.com/) - the free trial is fine - and setting up SSL proxying on the device you run Apollo on.

If you don't want to or care to do this, it should be fine. I remember Christian saying that the average Apollo user consumes around 350 API calls _per day_. 100 a minute for the free plan seems quite generous, considering this is Reddit, but some mod bots may need those to function.

**Comment by koassount** [comment]
@paradoxally @Rihcus 
It's like 60 a minute if you scroll like a manica...
https://streamable.com/lbhm1p

Edit:
To be fair. All those requests just go to the Apollo backend... the actual Reddit requests are even less
