### ISSUE TITLE
Apollo version 0.15.12 Disables all functionality except changing app icon once ios date passes June 30th

### ISSUE THREAD

**Issue by Barusu-rem** [EthanArbuckle/Apollo-CustomApiCredentials#8]
Apollo disables functionality if the ios date and time is set past June 30th (you can only buy wall papers or change icons). Versions 0.15.11 and lower are unaffected.

Is it possible to patch out the hardcoded shutdown (or would it be easier to tell people to use older versions of apollo)?

![IMG_884F2EA71EB7-1](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/124480833/1a8b556c-13fc-4c68-b61a-5ddb4f9dc5b2)

**Comment by paradoxally** [comment]
People should use 1.5.11 because it won't show that screen. Everything premium is unlocked on that version, so the issue with restoring purchases not working is unaffected.

1.5.12 is for people who need to migrate their Pixel Pal to the standalone app or decline refunds. It may be possible to patch out that screen, but we don't know what changes Christian has added behind the hood. He may have disabled the API layer past a certain date even with a new key.

Also, make sure you disable automatic app updates in the App Store or it will keep pushing you automatically to 1.5.12.

**Comment by koassount** [comment]
Yeah, just get an IPA with an older version. But what I don't understand yet is:

What are people using this "patched" version of Apollo with their own API key going to do when the Apollo backend dies? The app currently doesn't directly communicate with the Reddit backend but with https://apolloreq.com/api/req_v2 and https://apollogur.download/api and so on... How is this going to help anyone when the dev shuts down his servers?

**Comment by paradoxally** [comment]
@koassount 

What we need to figure out is if those endpoints are absolutely necessary for the app to work properly. They could be just for logging or caching of images, requests, etc. I'm not entirely sure.

If they are app-breaking, I don't think there's much you can do unless the published backend code handles those endpoints. Theoretically, you could self-host it and replace the base URL Apollo points to. But that's not exactly a trivial task.

**Comment by koassount** [comment]
> @koassount
> 
> What we need to figure out is if those endpoints are absolutely necessary for the app to work properly. They could be just for logging or caching of images, requests, etc. I'm not entirely sure.
> 
> If they are app-breaking, I don't think there's much you can do unless the published backend code handles those endpoints. Theoretically, you could self-host it and replace the base URL Apollo points to. But that's not exactly a trivial task.

There is not a single request going directly to Reddit from the Apollo app... so yeah... 
I've never seen anyone actually post a video/log of the traffic so I made a short one and posted it ->
https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/issues/7#issuecomment-1614826429

**Comment by Rihcus** [comment]
> > @koassount
> > What we need to figure out is if those endpoints are absolutely necessary for the app to work properly. They could be just for logging or caching of images, requests, etc. I'm not entirely sure.
> > If they are app-breaking, I don't think there's much you can do unless the published backend code handles those endpoints. Theoretically, you could self-host it and replace the base URL Apollo points to. But that's not exactly a trivial task.
> 
> There is not a single request going directly to Reddit from the Apollo app... so yeah... I've never seen anyone actually post a video/log of the traffic so I made a short one and posted it -> [#7 (comment)](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/issues/7#issuecomment-1614826429)

https://imgur.com/a/oYnk1x0

oath.reddit.com seems to be used. Apollo req actually responds with connection errors

![A2IUvWo](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/30292597/826eea61-517e-4bac-8d9d-bf6e793f6b00)

**Comment by koassount** [comment]
> > > @koassount
> > > What we need to figure out is if those endpoints are absolutely necessary for the app to work properly. They could be just for logging or caching of images, requests, etc. I'm not entirely sure.
> > > If they are app-breaking, I don't think there's much you can do unless the published backend code handles those endpoints. Theoretically, you could self-host it and replace the base URL Apollo points to. But that's not exactly a trivial task.
> > 
> > 
> > There is not a single request going directly to Reddit from the Apollo app... so yeah... I've never seen anyone actually post a video/log of the traffic so I made a short one and posted it -> [#7 (comment)](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/issues/7#issuecomment-1614826429)
> 
> https://imgur.com/a/oYnk1x0
> 
> oath.reddit.com seems to be used. Apollo req actually responds with connection errors
> 
> ![A2IUvWo](https://user-images.githubusercontent.com/30292597/250139378-826eea61-517e-4bac-8d9d-bf6e793f6b00.png)

Yeah just tested it with the Apollo APIs directed at localhost in my hosts file and it works fine.

**Comment by paradoxally** [comment]
@koassount 

I noticed in the screenshot that the calls to Apollo's servers are POST requests, so the app is likely sending some info back to Christian (possibly logging?).

Is it possible to see the request body the app sends to Apollo's servers? @Rihcus

**Comment by koassount** [comment]
> @koassount
> 
> I noticed in the screenshot that the calls to Apollo's servers are POST requests, so the app is likely sending some info back to Christian (possibly logging?).
> 
> Is it possible to see the request body the app sends to Apollo's servers? @Rihcus

Yeah, you're correct. It's just some logs and the App works fine even if the official (Apollo) APIs are blocked.


request body:
```JSON
{
    "anonID": "C3B4D9ED-A52B-5C31-BADD-2417A5D6F7288",
    "endpoint": "api/info",
    "rateUse": "unset",
    "state": "free"
}
```
or
```JSON
{
    "anonID": "C3B4D9ED-A52B-5C31-BADD-2417A5D6F7288",
    "endpoint": "message/inbox",
    "rateUse": "unset",
    "state": "free"
}
```

Dumb mistake on my part. 👍

**Comment by Barusu-rem** [comment]
Not sure if allowed to link this but I linked decryped versions of apollo versions 0.15.11 and 0.15.9
https://github.com/Barusu-rem/apollo-decrypt-legacy-version/releases/tag/production

**Comment by EthanArbuckle** [comment]
this repo now contains a v1.15.11 build

**Comment by Rihcus** [comment]
> @koassount
> 
> I noticed in the screenshot that the calls to Apollo's servers are POST requests, so the app is likely sending some info back to Christian (possibly logging?).
> 
> Is it possible to see the request body the app sends to Apollo's servers? @Rihcus

Just want confirm apollo is currently proper shutdown (logging into the unmodded main app leads to crashing) while in contrast the modded app works normal.
