### ISSUE TITLE
Apollo no longer works

### ISSUE THREAD

**Issue by vitamoon** [EthanArbuckle/Apollo-CustomApiCredentials#9]
on version 1.15.11

Was working fine just a few minutes ago, then got logged out and see this screen. Probably Christian shut down something necessary on the backend?

![IMG_5415](https://github.com/EthanArbuckle/Apollo-CustomApiCredentials/assets/91440012/dde14cf7-f6c7-46f8-8448-73c268239a1f)

**Comment by paradoxally** [comment]
That's weird. The official app still works for me with no modifications (no API key change). 

I force quit and restart, v 1.15.11.

**Comment by vitamoon** [comment]
Actually I checked and you're right, it does seem to be working right now. I probably messed something up recently and will update if I find it.

**Comment by iGerman00** [comment]
Having this issue as well
